version: '3'

services:
  nodejs:
    image: node:latest
    container_name: iot-manager
    volumes:
      - .:/app
    networks:
      - contreaul-net
    working_dir: /app
    env_file:
      - .env
    environment:
      - SOCKET_PORT=5000
      - API_URL=http://51.83.41.102
      - API_PORT=8080
    ports:
      - 5000:5000
    command: sh -c "npm install && npm run start"

networks:
  contreaul-net:
    name: database_contreaul-net
    external: true
